#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PORT="${RB_BLOG_PORT:-8090}"
ADDR="127.0.0.1:${PORT}"
BASE_URL="http://${ADDR}"
DB_PATH="${RB_BLOG_DB:-$(mktemp "${TMPDIR:-/tmp}/rusty-base-blog.XXXXXX")}"
SERVER_LOG="$(mktemp "${TMPDIR:-/tmp}/rusty-base-blog-server.XXXXXX")"
SSE_LOG="$(mktemp "${TMPDIR:-/tmp}/rusty-base-blog-sse.XXXXXX")"
COVER_FILE="$(mktemp "${TMPDIR:-/tmp}/rusty-base-cover.XXXXXX")"
SERVER_PID=""
SSE_PID=""

cleanup() {
  if [[ -n "${SSE_PID}" ]] && kill -0 "${SSE_PID}" 2>/dev/null; then
    kill "${SSE_PID}" 2>/dev/null || true
    wait "${SSE_PID}" 2>/dev/null || true
  fi
  if [[ -n "${SERVER_PID}" ]] && kill -0 "${SERVER_PID}" 2>/dev/null; then
    kill "${SERVER_PID}" 2>/dev/null || true
    wait "${SERVER_PID}" 2>/dev/null || true
  fi
  rm -f "${DB_PATH}" "${SERVER_LOG}" "${SSE_LOG}" "${COVER_FILE}"
}
trap cleanup EXIT

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "missing required command: $1" >&2
    exit 1
  fi
}

json_get() {
  python3 -c '
import json
import sys

value = json.load(sys.stdin)
for part in sys.argv[1].split("."):
    if part:
        value = value[int(part)] if part.isdigit() else value[part]
print(value)
' "$1"
}

sse_client_id() {
  python3 -c '
import json
import sys

try:
    text = open(sys.argv[1], encoding="utf-8").read()
except FileNotFoundError:
    sys.exit(1)

for line in text.splitlines():
    if line.startswith("data: "):
        try:
            data = json.loads(line[6:])
        except json.JSONDecodeError:
            continue
        client_id = data.get("clientId")
        if client_id:
            print(client_id)
            sys.exit(0)
sys.exit(1)
' "$1"
}

api_json() {
  local method="$1"
  local path="$2"
  local body="$3"
  curl -fsS -X "${method}" "${BASE_URL}${path}" \
    -H "content-type: application/json" \
    -d "${body}"
}

api_json_auth() {
  local method="$1"
  local path="$2"
  local token="$3"
  local body="$4"
  curl -fsS -X "${method}" "${BASE_URL}${path}" \
    -H "authorization: Bearer ${token}" \
    -H "content-type: application/json" \
    -d "${body}"
}

wait_for_server() {
  for _ in $(seq 1 80); do
    if curl -fsS "${BASE_URL}/api/health" >/dev/null 2>&1; then
      return
    fi
    if [[ -n "${SERVER_PID}" ]] && ! kill -0 "${SERVER_PID}" 2>/dev/null; then
      echo "server exited before becoming ready" >&2
      tail -n 80 "${SERVER_LOG}" >&2 || true
      exit 1
    fi
    sleep 0.25
  done

  echo "server did not become ready at ${BASE_URL}" >&2
  tail -n 80 "${SERVER_LOG}" >&2 || true
  exit 1
}

wait_for_client_id() {
  for _ in $(seq 1 80); do
    if client_id="$(sse_client_id "${SSE_LOG}" 2>/dev/null)"; then
      echo "${client_id}"
      return
    fi
    sleep 0.1
  done

  echo "realtime client id was not received" >&2
  cat "${SSE_LOG}" >&2 || true
  exit 1
}

wait_for_realtime_event() {
  local needle="$1"
  for _ in $(seq 1 80); do
    if grep -Fq "${needle}" "${SSE_LOG}"; then
      return
    fi
    sleep 0.1
  done

  echo "realtime event not observed: ${needle}" >&2
  cat "${SSE_LOG}" >&2 || true
  exit 1
}

require_command cargo
require_command curl
require_command python3
require_command grep

cd "${ROOT_DIR}"
printf '# Rusty Base blog demo\n\nProtected attachment generated by examples/blog.sh.\n' > "${COVER_FILE}"

echo "Starting Rusty Base server on ${BASE_URL}"
cargo run -p rb-server -- serve "${DB_PATH}" "${ADDR}" >"${SERVER_LOG}" 2>&1 &
SERVER_PID="$!"
wait_for_server

echo "Creating auth, relation, file, and comment collections"
api_json POST /api/collections '{"name":"users","type":"auth","fields":[{"name":"email","type":"email"},{"name":"name","type":"text"},{"name":"verified","type":"bool"}]}' >/dev/null
api_json POST /api/collections '{"name":"tags","fields":[{"name":"label","type":"text"}]}' >/dev/null
api_json POST /api/collections '{"name":"posts","fields":[{"name":"title","type":"text"},{"name":"published","type":"bool"},{"name":"author","type":"relation","collection":"users","maxSelect":1},{"name":"tags","type":"relation","collection":"tags","maxSelect":5},{"name":"cover","type":"file","maxSelect":1,"protected":true,"mimeTypes":["text/markdown"]}],"listRule":"published = true || author = @request.auth.id","viewRule":"author = @request.auth.id","createRule":"author = @request.auth.id","updateRule":"author = @request.auth.id","deleteRule":"author = @request.auth.id"}' >/dev/null
api_json POST /api/collections '{"name":"comments","fields":[{"name":"body","type":"text"},{"name":"post","type":"relation","collection":"posts","maxSelect":1},{"name":"author","type":"relation","collection":"users","maxSelect":1}],"listRule":"author = @request.auth.id","viewRule":"author = @request.auth.id","createRule":"author = @request.auth.id"}' >/dev/null

echo "Creating a user and logging in"
api_json POST /api/collections/users/records '{"id":"user_1","email":"writer@example.com","name":"Writer","verified":true,"password":"correct horse","passwordConfirm":"correct horse"}' >/dev/null
TOKEN="$(api_json POST /api/collections/users/auth-with-password '{"identity":"writer@example.com","password":"correct horse"}' | json_get token)"
echo "Auth token: ${TOKEN:0:12}..."

echo "Creating tags and a protected blog post"
api_json POST /api/collections/tags/records '{"id":"tag_rust","label":"rust"}' >/dev/null
api_json POST /api/collections/tags/records '{"id":"tag_sqlite","label":"sqlite"}' >/dev/null
api_json_auth POST /api/collections/posts/records "${TOKEN}" '{"id":"post_1","title":"Rusty Base demo","published":true,"author":"user_1","tags":["tag_rust","tag_sqlite"]}' >/dev/null

COVER_RESPONSE="$(curl -fsS -X PATCH "${BASE_URL}/api/collections/posts/records/post_1" \
  -H "authorization: Bearer ${TOKEN}" \
  -F "cover=@${COVER_FILE};type=text/markdown")"
COVER_NAME="$(printf '%s' "${COVER_RESPONSE}" | json_get cover)"
echo "Protected file stored: ${COVER_NAME}"

NO_TOKEN_STATUS="$(curl -sS -o /dev/null -w "%{http_code}" "${BASE_URL}/api/files/posts/post_1/${COVER_NAME}")"
if [[ "${NO_TOKEN_STATUS}" != "404" ]]; then
  echo "expected protected file without token to return 404, got ${NO_TOKEN_STATUS}" >&2
  exit 1
fi

FILE_TOKEN="$(curl -fsS -X POST "${BASE_URL}/api/files/token" -H "authorization: Bearer ${TOKEN}" | json_get token)"
FILE_BYTES="$(curl -fsS "${BASE_URL}/api/files/posts/post_1/${COVER_NAME}?token=${FILE_TOKEN}" | wc -c | tr -d ' ')"
echo "Protected file download with token: ${FILE_BYTES} bytes"

echo "Reading expanded post list"
EXPANDED_TOTAL="$(curl -fsS "${BASE_URL}/api/collections/posts/records?expand=author,tags&filter=author%20%3D%20%27user_1%27" \
  -H "authorization: Bearer ${TOKEN}" | json_get totalItems)"
echo "Expanded posts visible to owner: ${EXPANDED_TOTAL}"

echo "Opening realtime stream and subscribing to comments/*"
curl -fsS -N "${BASE_URL}/api/realtime" >"${SSE_LOG}" 2>/dev/null &
SSE_PID="$!"
CLIENT_ID="$(wait_for_client_id)"
api_json_auth POST /api/realtime "${TOKEN}" "{\"clientId\":\"${CLIENT_ID}\",\"subscriptions\":[\"comments/*\"]}" >/dev/null

api_json_auth POST /api/collections/comments/records "${TOKEN}" '{"id":"comment_1","body":"First comment from the demo","post":"post_1","author":"user_1"}' >/dev/null
wait_for_realtime_event '"action":"create"'
wait_for_realtime_event '"id":"comment_1"'
echo "Realtime comment create event received"

COMMENTS_TOTAL="$(curl -fsS "${BASE_URL}/api/collections/comments/records?expand=post,author" \
  -H "authorization: Bearer ${TOKEN}" | json_get totalItems)"
echo "Expanded comments visible to owner: ${COMMENTS_TOTAL}"

echo
echo "Rusty Base blog demo completed successfully."
